### ISSUE TITLE
0.0.1-alpha.11 breaks - can't init manager (context: Next.js)

### ISSUE THREAD

**Issue by jashmenn** [ifiokjr/remirror#74]
## Description

👋 Something in `0.0.1-alpha.11` breaks when running in Next.js.

Here's a minimal repo that reproduces the problem:

https://github.com/jashmenn/loading-issue-ignore-this/tree/remirror%400.0.1-alpha.11

Fwiw, it works just fine on `remirror@0.0.1-alpha.10`. [alpha.10 repo branch here](https://github.com/jashmenn/loading-issue-ignore-this/tree/remirror%400.0.1-alpha.10)

### Stack Trace
```text
Cannot read property 'init' of undefined
TypeError: Cannot read property 'init' of undefined
    at new Remirror (/Users/nmurray/tmp/loading-issue-ignore-this/next-app/node_modules/@remirror/react/lib/components/remirror.js:281:19)
    at processChild (/Users/nmurray/tmp/loading-issue-ignore-this/next-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2829:14)
    at resolve (/Users/nmurray/tmp/loading-issue-ignore-this/next-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2795:5)
    at ReactDOMServerRenderer.render (/Users/nmurray/tmp/loading-issue-ignore-this/next-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3185:22)
    at ReactDOMServerRenderer.read (/Users/nmurray/tmp/loading-issue-ignore-this/next-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3144:29)
    at renderToString (/Users/nmurray/tmp/loading-issue-ignore-this/next-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3629:27)
    at render (/Users/nmurray/tmp/loading-issue-ignore-this/next-app/node_modules/next-server/dist/server/render.js:42:16)
    at renderPage (/Users/nmurray/tmp/loading-issue-ignore-this/next-app/node_modules/next-server/dist/server/render.js:102:16)
    at Function.getInitialProps (/Users/nmurray/tmp/loading-issue-ignore-this/next-app/.next/server/static/development/pages/_document.js:199:25)
    at Object.loadGetInitialProps (/Users/nmurray/tmp/loading-issue-ignore-this/next-app/node_modules/next-server/dist/lib/utils.js:45:35)
    at Object.renderToHTML (/Users/nmurray/tmp/loading-issue-ignore-this/next-app/node_modules/next-server/dist/server/render.js:106:36)
```

![localhost_3000](https://user-images.githubusercontent.com/4318/55592661-b9c6b480-56fe-11e9-8aca-e78bb36668ba.png)

![localhost_3000 2](https://user-images.githubusercontent.com/4318/55592666-bf23ff00-56fe-11e9-854d-9153f057ef62.png)

**Comment by ifiokjr** [comment]
Thanks for raising the issue. 

The API changed quite significantly between `alpha.10` and `alpha.11`. It's now (imo) a better fit with the react component model, but it does require some changes to get things working. 

This was definitely a huge breaking change. See (#64) for an outline on some of the motivations.

The main change is that the foundational `Remirror` component now expects a `manager` instance rather than an array of extensions to be passed through. To make this easier there are some new components which perform most of the work for you.

- `RemirrorManager` - Injects an  ExtensionManager instance into the react context. 
- `RemirrorExtension` - Enables instantiating extensions automatically without the need of using classes. So nor more `new Mention({ onKeyDown: () => { ...[complex function] } })`. These must be direct children of the `RemirrorManager`.
- `ManagedRemirrorEditor` - Automatically pulls in the extension manager instance from the context and passes it to the underlying Remirror component while also making the Remirror context available to be used in the rest of the application.
- Extensions can now be instantiated with a priority. A lower number means the extension has a higher preference. 
- A recommendation to use hooks as they make extracting context much simpler. 

Take a look at the following example for some inspiration. 

https://github.com/ifiokjr/remirror/blob/3b48d6de322e7be0f9b2ee1f8ab7fdea9792384c/%40remirror/ui-wysiwyg/src/components/editor.tsx#L77-L100

Using the new API, the maintainability and readibility of ui code significantly improved according to [codeclimate](https://codeclimate.com/github/ifiokjr/remirror/progress/maintainability). It's now much easier to manage callbacks and to split up complex editors into smaller chunks. 

![image](https://user-images.githubusercontent.com/1160934/55599435-b576b780-574f-11e9-9447-b95744a42e74.png)


**PS:** I've just started on a complete rewrite of the documentation which includes:

- [tsdocs](https://github.com/Microsoft/tsdoc) generated from the code.
- Walkthrough guides and a better explanation of the underlying concepts
- A custom docs theme for better navigation and explanation of what Remirror offers
- A short introductory video tutorial on how to get started with Remirror.
- A new URL (remirror.org instead of docs.remirror.org)
- An actual **changelog** 😄 

I also don't expect any further large API changes before the first stable release of `remirror@0.1.0`.

**Comment by jashmenn** [comment]
Ah! Okay great. I will swap this over. Thanks!
